#+title: Голое железо (эссе об Emacs)
#+date: 2025-08-01
#+language: ru

/01 августа 2025/

Перед вами — фрагмент для «Emacs Carnival» Джереми Фризена, на сей раз на тему «речи в лифте». Этот кусок извлечён из необъятной рукописи в работе («настоящая работа») — условно озаглавленной «Волнующая паника!». Главу я начал в конце 2022 года. Вечно вынашивать нельзя.

Книга — о магии и прочих антирациональных практиках и верованиях.

Если нужна предельно краткая «речь в лифте» о Emacs, вот она: «Это свободный текстовый редактор с открытым кодом, где можно менять даже основы поведения — налету, правя его изнутри. Поначалу он заметно сложнее, чем VS Code и прочие, но овладев, вы, вероятно, получите самое мощное из доступных пользователю приложений. И, как ни странно, это ещё и просто отличный редактор текста». Считайте это моей лифтовой речью — в «Большом стеклянном лифте» (Роальд Даль).

Глава тянет слов на одиннадцать тысяч и в охвате широка. Толкнул же меня поделиться именно сейчас — Джереми: я много лет живу под светом его заметок про OSR (Old School Renaissance), и в этом тексте есть несколько пассажей, что прямо бегут навстречу нашему взрослому общему увлечению.

Спасибо за чтение — и Джереми за площадку.

#+begin_quote
За четверть века мы поняли вот что: доступа к инструментам и идеям мало. Рука и рассудок оттачиваются не столько теорией, сколько упражнением; мастерство приходит с практикой, с ней же — особая чуткость. Потому и сменили мы девиз: с прежнего «доступ к инструментам и идеям» — на «доступ к идеям, инструментам и практикам». (Whole Earth, №90, лето 1997)

Где-то к 1995-му — поминаю этот год не зря, «год Интернета» — стало совершенно ясно, что мы катимся к тому, что я теперь зову технопатократией, «властью больных машин», а попросту — властью денег. (Питер Лэмборн Уилсон)

Вселенная выдыхается. Таково её устройство. (Джон М. Форд, «Против энтропии»)
#+end_quote

* В дебри

В сорок с лишним я намеренно взялся за несколько долгих, десятилетних проектов: хотел овладеть горсткой инструментов и текстов, к которым всю жизнь тянуло меня сбоку поля зрения, требуя не поверхностного зазнайства, а преданного, вдумчивого ученичества. И все они — как водится — собрались в этой книге.

Тяготею к чистому тексту и редакторам «программистского толка»: люблю писать без прикрас; предпочитаю те программы, где «горячие клавиши» одинаково годятся и для прозы, и для кода.[fn:1] Первые годы весь этот замысел плёлся в Sublime Text — он для кода, но, признаться, и прозе в нём легко дышится: тишина, никаких уведомлений. Есть, правда, «редакторские» привычки, плохо переводимые на прозу: скажем, понятие «строки» — в литературе мы живём абзацами, длинными, переливчатыми, как река. А непрограммисты, как правило, избегают редакторов для кода — тянет их к родному, к Microsoft Word. Но у всякого своя тропа.

Десятилетие Sublime служил мне верой и правдой, но его разработка стала буксовать: программа стареет быстрее нас; ей скоро на покой, а мне, выходит, заново осваивать чужие причуды — удовольствие ниже среднего. В сорок три учиться — не сахар, а в пятьдесят три — и подавно. К чёрту.

Я на время закрутил роман с Vim.

В Vim нажатия не порождают буквы — они выполняют команды: hjkl двигают курсор, x удаляет символ, X стирает назад, / запускает поиск по регулярным выражениям. Чтобы вернуться к набору текста, надо нажать i (или a и т. п.) и перейти в Insert. В обычном редакторе первичен набор, правка — довесок; в Vim манипуляция текстом — действие первого класса. Главное — команды сочетаются: d$ удаляет до конца строки, di) — содержимое скобок, da) — то же вместе со скобками. Для тех, кто бездумно настрочил эссе в MS Word и не оглянулся, модель сперва нелепа; для программистов — ложится в руку. На работу мастеров Vim страшно смотреть.

Но не моё: монастырский устав мне не по нутру. Почувствовав лёгкий укол самоиронии (а может, сказалось бывшекатолическое, слегка мазохистское настроение), я вернулся к инструменту, что служил мне в девяностых: Emacs — удивительный редактор: расширяемый, настраиваемый и самодокументированный.

* Биографическое уточнение

В ближайшие десять тысяч слов мы будем называть хакера и основателя Free Software Foundation Ричарда Столлмана создателем Emacs. В семидесятые он был крупной фигурой контркультуры вычислений; о его сложном влиянии на движение свободного/открытого ПО девяностых можно сказать многое.

Столлман был не единственным автором Emacs, но по роли в судьбе проекта — и в некотором смысле — стал его создателем. Так жизнь распорядилась. В духе традиций Лаборатории ИИ MIT того времени над «?MACS» трудилась горстка разработчиков, которые сначала расширили древний редактор TECO, а затем переросли его; в AI Lab «rms» считался «первым среди равных» в той когорте и мог в 1976 году, с согласия соавтора Гая Стилла («gls», позже вместе с Джеральдом Сассманом создавшего Scheme), переименовать ?MACS в «Emacs». Джеймс Гослинг — будущий отец Java — в начале восьмидесятых написал свою версию Emacs, которую Столлман почти целиком переписал и в 1985-м, по своим строгим этико-юридическим принципам, выпустил как GNU Emacs. Как писал Стилл в 2007-м:

#+begin_quote
RMS всё равно заслуживает 99% или 99.9% или 99.99% или 99.999% заслуг за то, что взял пакет макросов TECO и дважды превратил его в самый мощный редактор на планете (сначала в TECO, потом на ELISP)… Не думаю, что у RMS есть причины отрицать должную долю заслуг людей, помогавших ему в первые месяцы. Они дарили своё время и творчество безвозмездно, в лучшем духе вклада в сообщество.
#+end_quote

Из более полной хроники этой истории можно извлечь уроки: о коллективном вдохновении и «сценичности» Брайана Ино; об управлении напряжением между личной собственнической гордыней и публичным принципом; о строительстве «намеренного интеллектуального сообщества», когда вокруг — тьма денег; о том, как аутизм и проблемы исполнительных функций оформили раннюю «гиковскую» культуру, и как мейнстрим (монетизируя/уничижая) ответил на эти когнитивные особенности. Позднейшая история Столлмана, включая недавний скандал, из-за которого его на время отлучили от движения свободного ПО, — занятный кейс. Но не здесь.

* YAFIYGI [fn:yafiygi]

[fn:yafiygi] Акроним от «You Asked For It, You Got It» — «Сам просил — сам и получай». В жаргоне Emacs: «хотел полной настраиваемости — получи и ответственность за неё».

Об Emacs ходит дурная слава: мол, он медленный, корявый, древний, непостижимый, бессмысленно сложный, эргономически катастрофический и просто уродливый. Ничего из этого не верно, хотя ясно, откуда берутся такие впечатления:

- Новичок в Emacs всё делает медленно — непривычно, вид аскетичен, «строительных лесов» для неофита нет.
- Его текстовая суровость и свой жаргон («kill» вместо «cut»? «window» — не «окно»?) создают видимость доисторического софта, хотя его неустанно полируют.
- Команды-клавиатурные аккорды[fn:3] — скажем, C‑c C‑a f для сноски в буфере Markdown или C‑x C‑f для открытия файла — и непривычны, и на вид громоздки, будто придуманы под инопланетные клавиатуры[fn:4] (и руки); их эргономика кажется безумной, а обнаруживаемость[fn:5] — кошмарной.
- Обычные элементы интерфейса в Emacs «говорят» на странном диалекте; его частные идиомы выглядят сложнее или попросту произвольно отличными от консенсусного языка коммерческого ПО. Разделите фрейм надвое (то есть на два «окна» Emacs), «убейте» (kill) одно — и исчезнут оба, по вполне логичным причинам, которые для непосвящённого смысла не имеют.[fn:6]
- А для современного глаза — от стены ASCII в терминале до нелепых вкладок — Emacs просто некрасив; у тех же, кто принимает «утончённость» за причёсанный вид и правильные словечки вместо работы, это поднимается от вкуса до религии.

Проще говоря, Emacs, как и Дрю Бэрримор, под пятьдесят, и выглядит он соответственно; пользователи, приходящие из «современного» коммерческого софта, — словно горожане, которых заставили выдернуть вилку из микроволновки и вспомнить, что такое огонь. Микроволновка упрощает сложное, ускоряет медленное, делает плохое терпимее; но без прочих инструментов хорошего ужина не будет. А когда море поднимется и свет погаснет, микроволновка останется разве что будкой для мелких питомцев. Огонь — останется.

#+begin_quote
Без огня не правят.
#+end_quote

И всё-таки я не пытаюсь «продать» вам Emacs. Как и Столлман, и сам редактор, мы имеем в виду другое.

* Воплощённая философия

Пользоваться Emacs — значит иметь дело с системой, не похожей ни на какое сопоставимое по мощи ПО: построенной вокруг интроспекции — самонаблюдения, когда редактор показывает и правит собственный код — и беспримерной расширяемости. Представьте: вы сохраняете документ, а потом набираете букву s. В Emacs, как и в MS Word или почти где угодно, вы жмёте «сохранить» (здесь ~C‑x C‑s~), документ пишется на диск, а затем вы набираете s — и на экране появляется «s», что естественно. Почти ни в какой программе нельзя перенастроить это поведение: Ctrl‑S/Cmd‑S — «Сохранить», «s» — «s». Коснулся клавиши — получил букву. Таков контракт.

В Emacs, когда вы жмёте C‑x C‑s, вызывается функция ~save-buffer~ — небольшая функция на Emacs Lisp, исходник которой в файле ~files.el~:

#+begin_src elisp
(defun save-buffer (&optional arg)
 (interactive "p")
  (let ((modp (buffer-modified-p))
    (make-backup-files (or (and make-backup-files (not (eq arg 0)))
                   (memq arg '(16 64)))))
    (and modp (memq arg '(16 64)) (setq buffer-backed-up nil))

    (if (and modp
             (buffer-file-name)
             (not noninteractive)
             (not save-silently))
    (message "Saving file %s..." (buffer-file-name)))
    (basic-save-buffer (called-interactively-p 'any))
    (and modp (memq arg '(4 64)) (setq buffer-backed-up nil))))
#+end_src

(Подробная самодокументация функции опущена ради краткости; «docstring», отличный от комментариев в исходнике, — одна из ранних важных инноваций Emacs.)

Вы можете не только править приведённый код — что вообще верно для любого софта, который вы сами собираете, — но можете делать это естественно, налету, не выходя из Emacs, например, с помощью механизма «advice» — перехватов/обёрток функций. Написав сколь угодно хитрый лисп-код, вы можете дополнять, перехватывать, оборачивать или вовсе подменять ~save-buffer~ своим вариантом, меняя поведение Emacs по ходу пьесы. Не чувствуете, почему это важно? Представьте, что в телефоне вы могли бы переопределить, какие именно данные уходят в сеть при нажатии «Отправить» в мессенджере. Представьте, что в консоли разработчика Chrome вы могли бы переписать гугловский трекинговый код — или вырвать его с корнем…

Но и этого мало: когда вы набираете самую обычную букву s в такой вот фразе, Emacs вызывает функцию ~self-insert-command~. Да, коротенькую программу на Emacs Lisp — и да, её тоже можно править на лету. Хотите, чтобы Emacs заменял буквы по контексту (или по времени суток), центрировал окно на начале нового абзаца, ограничивал число восклицательных знаков уже в процессе набора, вёл журнал ваших нажатий и строил по нему графики, или заставлял делать паузы «по Помодоро» переменной длины в зависимости от задачи? Всё это возможно, потому что хранители Emacs десятилетиями настаивали на таких возможностях — из философских соображений.

Этот доступ к внутренностям — больше, чем «настраиваемость», хотя и это — удобная продающая строка. Обычные разработчики решают, как будет работать их программа: определяют глаголы и объекты и базовую логику взаимодействия (UX), а вам, пользователю-потребителю, позволяют менять лишь некоторые наречия — цвет экрана, скажем. (Не угодно ли свеженький «тёмный режим»? Наш Дизайн-комитет подобрал прекрасную палитру…) Ричард Столлман с товарищами создали и поддерживают — ценой времени и нервов — систему, в которой пользователь может исполнять сколь угодно сложные программы поверх буферно-оконной рамки Emacs, выбирая свои — чёрт возьми — глаголы и определяя работу программы до самого нижнего практического уровня.[fn:7]

Есть старая шутка: «Emacs — отличная операционная система, которой не хватает лишь приличного текстового редактора». Пойдём дальше, но вбок: Emacs — это труд воплощённой философии, способ жить свободно (ему не хватает только приличного редактора).

Его установки — намеренно основополагающие: Emacs — свободный проект под эгидой Free Software Foundation Столлмана, организации, посвятившей себя радикальному тезису: скачав программу, вы должны иметь возможность делать с ней всё, на что способны — и над ней, и с её помощью. Иначе говоря: вы обязаны владеть и контролировать свои данные и своё ПО; оно не должно контролировать вас. Free — и как «пиво», и как «слово». Способы, которыми Фонд проводит принципы, могут показаться драконовскими: чтобы внести код в ядро Emacs, надо явно (и хлопотно) отказаться от «прав интеллектуальной собственности». Но делать по-правде — долго.

Emacs артикулирует философию свободы: человек не по-настоящему свободен, если у него нет полной приватности и полного контроля над своими инструментами. Потому весь Emacs прозрачен для изучения и интроспекции — до голого железа, до самого нижнего C-кода. Как бы ни была сложна среда, от пользователя ничего не прячут. Программа специально построена так, чтобы обеспечивать интроспекцию; предназначение её — не столько редактирование текста (в чём она сильна), сколько предоставление (воплощение) контроля над вычислением — прямо противоположного сегодняшним «огороженным садам». (Попробуйте достать сторонние запчасти для своей Tesla.) Этот замысел жизненно важен и крайне необычен нынче, когда и железные хакеры, и позёры носят футболки «I VIOLATE WARRANTIES» как знак гордого несогласия. Но он в полном духе семидесятых — движения за освобождающие персональные вычисления, за создание и распространение инструментов для роста человеческого здоровья и возможностей, а не для выжимания из нас рекламных денег. (Силиконовая долина просто отказалась от этого этоса — одна из причин, почему создатель Emacs вызывает у позёров смех.)

В Emacs можно сыграть в «Тетрис» прямо в буфере — потому что дозволено всё, что возможно; и да, по какой-то дурацкой причине «Тетрис» встроен. (Попробуйте M‑x tetris.)[fn:8]

Речь о сложной программной системе — по сути, об исполняющей среде Lisp, то есть программе для запуска других программ — у которой мощный текстовый редактор — главная, но не единственная функция.

#+begin_quote
Я вижу в Emacs по сути две вещи: программируемый рантайм и маяк свободного софта. (Мурило Перейра)
#+end_quote

Задача программы — даровать освобождающий опыт автономных вычислений. Сознание — то, чем заняты тела; а инструменты расширяют связку «тело–ум»: контроль над инструментами[fn:9] — это свобода.

Даже если вы не считаете вычисление разновидностью «внешней не-нейронной когнитивной активности» — а уж тем более если считаете, — Emacs можно понимать как уникальный инструмент свободного мышления, то есть воображательного усилия, ограниченного лишь мастерством владения средствами и приёмами, наделённого силой и не принуждаемого. Непроницаемый для непосвящённых, со своими сложными «заклинаниями», Emacs обнимает техники когнитивного преображения, не сводимые к земной задаче «редактирования текстов». По-настоящему вы начинаете им пользоваться, когда начинаете думать, как он — после чего трудно представить, что вы пересядете на что-либо иное, разве что по принуждению: прочий «подобный» софт скован более-менее благонамеренными рамками заданности и продаёт часть свободы за мгновенную пользу — то есть меняет полноту на удовлетворение. Emacs таков по философским причинам, и, оставаясь верным своим (то есть ФСФ, то есть Столлмана) принципам, умудряется одновременно артикулировать убеждения и быть, без шуток, мощным инструментом, которым приятно пользоваться и овладевать. Когда старые волки говорят, что Emacs — единственная программа, которая им нужна в рабочий день, они имеют в виду: это целая система (по сути «операционная система»), под сенью которой можно делать и прочее. Способ бытия.

Программист и брюзга Стив Йегги как-то описал Emacs как

#+begin_quote
нечто среднее между Блокнотом Windows, операционной системой с монолитным ядром и Международной космической станцией…
#+end_quote

…но другой зануда вспомнил бы скорее замок Горменгаст, а не МКС — строение-мир, вывёрнутый дворец памяти, где метод loci не только запоминает, но и производит гротескную странность. Десятилетиями нарастает кое-как, едва держась, как угасающая империя (или орбитальная лаборатория), будто бы автокаталитичен, способен порождать внутри новые причудливые реальности. Бесконечен и едва сам себя удерживает.

(Мне вспоминаются «Эджвуд» Джона Краули, «Пиранези» Сюзанны Кларк, дом Навидсонов — и, конечно, LambdaMOO и его объект №17, Гостиная.)

И теперь, если вы с нами по ходу настоящей работы, самое время снова подумать о «магии» — в частности о магии как воображаемой (анти)системе. С акцентом на самоопределении, перекройке себя, интроспекции и «любви под волей» естественно рассматривать Emacs как разновидность магической системы — целую альтернативную область, требующую труда для осмысления, — которая, однажды понятая, позволяет породить что угодно. Им можно править текстовые файлы — даже на человеческих языках,[fn:10] — но это всё равно что «прибегать к магии», чтобы «сотворить приворот». Привороты — побочный продукт воображаемого преображения мага; если всё, чего вы хотите от магических изысканий, — чтобы кто-то вас полюбил, есть средства куда лучше: внимательный живой разговор, например. Требуется много труда, чтобы Emacs «просто работал», и так и должно быть: изучение Emacs — как Lisp или латыни, тантры или тарантеллы — само по себе задач не решает, оно открывает новые способы их решения. (Скорее мечта компьютерного учёного, чем прикладника.) В Lisp нет «синтаксического сахара» — он ничего не прячет, как лодка со стеклянным дном. На латыни уже не говорят, но почти все на Западе говорят на языках, в двери к которым она вставляет ключ. Медитация не «сделает вас спокойным», но она может научить, как обрести покой. Сила инструмента в том, что сильнее становитесь вы — более готовыми и способными взять подлинную ответственность за творчество, то есть более свободными.

Любое заклинание накладывается на заклинателя.

Магия «не работает», повторяем, — но работает. Точнее: настроив свои dotfiles (сознание, магическую систему, ящик с инструментами) «как надо», вы сможете сделать всё, что и хотели вначале, — но интереснее то, чего начнёт хотеться уже внутри, то, чего вряд ли вообразит кто-то hors-texte (даже если «вне текста» и существует).[fn:11] То, что становится возможным лишь в погружении, после (не)правильных инкантаций, открывающих нужное состояние. Вы отпускаете прежние желания и страх оценки — и обнаруживаете, что способны вообразить больше, чем знали. Отсюда различие между индустрией «персональных компьютеров» и движением «персональных вычислений»: первая — о покупке и употреблении инструментов; второе — о преображении и расширении «я» через их применение, о реализации человеческого потенциала… и как «побочный эффект» — об ослаблении тяги покупать дорогие товарчики у привычных хищников. Почему, как думаете, Они убили это движение…?

* Текстомиры

#+begin_quote
Вот так он видит всё время, каждый день. Будто тут только мы, внутри, вместе. … И у нас только мы и есть. (Лекс Лютор)
#+end_quote

В 1995-м я прошёл летний курс в Джонс Хопкинс под названием «Исследования текстовой виртуальной реальности» — о странных следствиях тогда ещё свежих онлайновых «мульти‑юзерских подземелий/доменов» (MUD), по сути многопользовательского «Зорка» в реальном времени. Читали мы Скотта Букатмана, Марка Дери, «Нейроманта», «Виртуальное сообщество» Рейнгольда, «Изнасилование в киберпространстве» Диббелла. Вкупе с моими параллельными тогдашними чтениями (Millennium Whole Earth Catalog, Principia Discordia, Revelation X, Usenet, ранняя Сеть) и с эротическим НФ‑триллером «Особь» с канадской моделью‑актрисой Наташей Хенстридж — это был опыт, изменивший жизнь.

В компьютерном классе JHU я узнал выражение «multi‑user shared hallucination» («коллективная общая галлюцинация») — MUSH; первоначально так называли вариацию MUD‑сервера, но в «настоящей работе» я употребляю его шире — не буду ходить вокруг да около: оно годится почти ко всему мне дорогому, ко всему хорошему и клёвому. Хотя в курсе мы занимались прежде всего MOO (MUD Object‑Oriented), в те головокружительные дни Whole Earth ’Lectronic Link и «Декларации независимости киберпространства» Барлоу было логично воспринимать само киберпространство — и глубоко странные культуры, самоорганизующиеся вокруг него — как одну и многие разновидности общей галлюцинации, распределённые техномагические эксперименты на границе виртуального пространства (внутреннего/головного не меньше, чем сетевого субстрата или словесной среды) и «мяса». Киберпространство было фантазией, ставшей явью — или, во всяком случае, сюр‑реальностью, напряжённым актом воображающей воли: нынче это звучит наивно, но тогда разумнее было говорить именно в таких терминах, насыщенных магическими возможностями, чем соглашаться на коммерческие или государственные предложения ограничить или приватизировать эту пограничную песочницу для связанных умов. Да, эмансипаторные возможности раннего киберпространства сами были общей галлюцинацией — как «шестидесятые» рядом с «1960‑ми»…

Любой акт коллективного рассказывания или фантастического созидания — партия в D&D или Nomic, магический ритуал, киберсекс, связь через доску уиджи или таро, выдуманный диалог на форуме, политический митинг, импровизационная музыка или комедия — можно (и должно) мыслить как разновидность инкантации или волевого психотропизма: коллективная общая галлюцинация. В «настоящей работе» термин «storygames» прикладывается к некоторым оккультным практикам (например, к «чэннелингу» на доске уиджи у Джеймса Меррилла и Дэвида Джексона); здесь хочется подчеркнуть именно текстовую связь между такими технологиями — то, как разделённые миры, сделанные из слов, — и чётких, и расплывчатых, индивидуальных и коллективных, формальных и лирических, музыкальных — похожи на магическую практику тем, как они деформируют восприятие и мышление вокруг фантастической реальности. Мемориальная словотворческая работа на расстоянии. Мы можем быть пересобраны из нереального вещества: помню, я расплакался, временно удалив своего персонажа на LambdaMOO где-то на рубеже тысячелетий — актом набора команд для прыжка с воображаемой скалы у дома Лямбда; помнится, это было похоже на чью‑то смерть — не совсем «человека», но и не просто «аккаунт на чат‑сервере». Помню, как читал «Вирикониум» под Chip‑Meditation в лобби отеля Disney World, потом катался на «It’s a Small World» и думал — знал, — что мы провалились в историю, плывём через одушевлённые руины Вечерних Культур, и сам Харрисон (тегеус‑Кромис? или Великий Каир?) должен был пройти тот же туннель воображаемо, если не телесно; история, ещё не рассказанная, как‑то снова рассказывалась…

~keyboard-quit~ — Чёрт, где это я? — ~pop-to-mark-command~


В повседневной работе Emacs как  призрачный лабиринт — смешно звучит, но именно так это и ощущается. Это мало связано с прикладной функцией и многое объясняет в его культе: близость к древнему двигателю; непостижимые, но внутренне логичные пассы руками; внезапные вспышки и исчезновения временных буферов; знание, что Emacs обволок десятки других систем и не насытился. Аскетичный вид — и немыслимое богатство  возможностей действия, почти внушающее талассофобию. В терминале он выглядит и ощущается как «лабиринт одинаковых извилистых ходов» из Zork. Отчасти это Emacs «говорит» визуальным языком своего времени и места; неизбежно вспоминаются Zork (1977), Rogue (1980), MUD1 (1978). Издалека, спустя десятилетия, Emacs и прочие текстомиры обретают археофутуристическое качество — как увидеть глиф R2D2 на каменной стене гробницы Ковчега Завета. Читается как запись обо всём мыслимом в ином моменте, как «Греческие мифы» Грейвса — вариантное моделирование чужого ума: Emacs — виртуальная реальность. Точнее, текстовая виртуальная реальность; снова 1995, если я вообще оттуда уходил…

Язык команд LambdaMOO или Zork прост до неприличия: S — чтобы GO SOUTH, SAY ABC — чтобы сказать «ABC» слушателям; но, как миф, глиф, «И‑цзин» или Lisp, он намекает на скрытую имплицитную систему; это «миростроительство» на уровне инструмента, а не описания или отсылки — выявленная структура аффордансов. Кто говорит на парсерском, думает мыслями парсера; парсер учит вас, как говорить с ним, что/как хотеть сказать, границам произносимого. Чертит дугу магического круга, сочетаемые ангельские руны. И вы стремитесь к опыту настолько реальному, насколько готовы — какова глубина погружения. Ключевой шаг к мастерству — решиться испытывать эти границы, тестировать VR, пока не упрётесь в «пузырь Трумана» (границу фикции; четвёртую стену) — и, услышав полый голос Кристофа: «ДУРАК!», повернуть назад и на время снова стать историей — остаться частью магии, ставшей вашей, практики в новом знании. Выучить новые правила, новый язык. (Подзаголовок Zork III — «Dungeon Master», и угадайте, чью работу вы берёте на себя, когда выигрываете игру?)

#+begin_quote
Я покажу этим людям то, чего ты не хочешь, чтобы они видели. Я покажу им мир без тебя… (Томас Андерсон)
#+end_quote

Мне нравится думать (иначе и быть не может!) о «системном воображаемом» — игривой, искусной установке на парсинг и контроль динамики сложных систем — будь то SimCity или, скажем, Nomic. Цель таких игр — «думать как система»: нащупать соответствие между вводом участника и откликом системы и применять его свободно, обитая в вынесенном когнитивном аппарате;[fn:12] может, яснее так: «чувствовать себя системой», соединяться со «вторым умом» в кремнии и ощущать поток информации как пульс, как хотение. Подумайте о «цеттелькастене», о симстим‑деках Молли, в «Нейроманте», как хакер Кейс (как и агент Смит в «Матрице») тащится от того, что занимает её тело… слёзы освобождения, когда Кейc вырывается из тюрьмы собственной плоти в абстрактный (бестелесный) ум матрицы у Гибсона или в заменитель сенсориума симстима. Я хочу верить (и чем раньше, тем лучше!), что мы всё ещё говорим об Emacs. В симулятивной игре «заимствованный» ум‑тело нечеловеческий, и соматическое — до эротического — наслаждение в восшествии/восприятии чуждой мыслящей системы за пределами антрокатегорий. Мы узнаём эту логику блаженного диалогического подчинения в «мистическом разговоре» поэта Руми[fn:13] с наставником Шамсом Тебризи — или (если угодно) в том, как Пол Муад’Диб поглощает свою предковую линию, мужскую и женскую, испив Воду Жизни. Молодые читатели, если таковые есть: помните, как Люк говорит Рей: «В тебе теперь живут тысячи поколений», а дальше она получает сверхсилы, но убивает своего парня на расстоянии и заканчивает фильм одна в пустыне среди призраков…? Психоделическое видение — антисистемный взгляд — делает вас страннее, и это того стоит: «Вот граница — и цена бессмертия».[fn:14]

Работая на краю системы, уверенно на незнакомом языке — в зоне ближайшего развития, — ощущаешь головокружение открытия и неведомости за пределом привычной способности, щепотку ужаса под кожей; смелые не лишены страха — они смотрят ему в лицо. Прирождённая многозначность текста/слова создаёт забавную размытость у кромки текстомира. То же с лоу‑фай‑графикой, гулким звуком: чем менее точно медиум воспроизводит сообщение, тем больше ответственности на получателе за сотворение смысла — воображательное конструирование сообщения и стоящих за ним намерений: «сотворение» одновременно «узаконяет‑устанавливает» и «наполняет влагой». Вы сливаетесь с сообщением. Тайна — в природе текста, в зазоре «медиум/месседж», и текстомиры — потому что они и есть и неизбежно не есть целиком на странице — всегда звучат/пахнут/видятся очень похоже на вас, Читатель(ей). Вы читаете тайну в бытие, в зазоры собственного восприятия и понимания; в интерактивном союзе с текстом (лексический «второй ум», внешняя система) вы затем переживаете эту тайну как конституирующую вас; всякий акт чтения или иной работы со словом опирается на надежду подобрать язык «достаточно правильно», не зная, что будет вызвано, если наложенные системы словоделания и смысла (явный и скрытый сон) чуууть не совпадут. Или совпадут. Вот странная мощь виртуальных мир‑слов: как они вцепляются в ваше воображение, вовлекают вас в сговор. Хотите вы того или нет.

Символы — великое дело.

Двадцать шесть букв, десять цифр, пригоршня завитков и чёрточек, табуляция/слэш — из этого кривого дерева сделать мир? Порядок? Научить машину, что делать, как хотеть? Наложить чары? Телетайп? Рассказать историю?

~M‑x yank-pop~?

Это качество — кидать монетки в темноту, чтобы понять, откинут ли их назад призраки; нащупывать набор тайных правил воображаемой трансформации, нажимать кнопки на заброшенном звездолёте, вдруг, вдруг, чтобы он взял и запустился — и, может быть, долетел до древнейшего света Вселенной; крутить ручку радио как раз так — всё это свойственно вчерашним виртуальностям. Новому миру руин требуется иное — «дружественная потребителю» переводимость/адаптируемость для внешних рынков или эквивалент. Режим обучения или проваливай, tl;dr. Нет рынков для тайны; нет времени для мечтаний — они принадлежали менее продуктивному старому миру.

Я ожидаю, что оно заработает «из коробки».

Я ожидаю нулевой задержки.

Я ожидаю отождествления с героем. Уверен, автор тоже.

Скажи мне, о чём будешь говорить, потом скажи, потом скажи, о чём сказал.

Проведи меня через самообучающиеся занятия.

Дааа, мне это нужно через час, спасибо.

…всё это — прямая противоположность плодотворной неточности магии, как порнография — противоположность эротике, а «спойлер» — «истории» (удивлению). Как система — софт, текстомир — цель которой решать за вас (ради вашего же блага), какие вопросы можно задавать, какие проблемы можно/нужно решать, — противоположность системе, цель которой — дать вам свободу, не зная, к чему это приведёт, если вообще приведёт. Доверяет вас морю. Свиваться со странностью системы — в этом смысл («сначала вникни в работу ~kill-ring~»), как и возможность вплести свою маленькую жизнь в другого человека и вокруг него — зачем ещё любить. Союз с другим, узнавание, резонанс, регуляция, ревизия.[fn:15] Значимая автономия — чудовищна, как сказал чьей‑то брат или иной, — даже более чудовищна, чем печатать ~C‑x C‑f~, чтобы открыть файл…

Оно прямо здесь, ~defun save-buffer (&optional arg)~ — ответ иллюстрирован: «киллер‑фича» Emacs — интроспекция и ужасная свобода, которую она даёт: сделай своим, сделай собой, почини, сломай, узнай, иди дальше и внутрь — и когда мы говорим «Да, конечно, оно так; магия — это набор инструментов для достижения внутреннего зрения/понимания, то есть самопознания», — пусть эти слова резонируют друг с другом. Надежда на язык осмысления и самоконструирования: интроспективное наделение силой.

Мы ведь всего лишь говорим о «свободном софте». Свобода как обретение.

* Эксплицитность

Сейчас поговорим об эзотерике. Но сперва — о посудомоечных машинах.

Прежде, покупая посудомоечную машину, вы получали и схемы. Сломалась — попробуй починить сам; бумага гарантировала принципиальную понятность внутренних дел, при известном усердии, — и возможность модификаций, если хватит амбиций. Не только из‑за отсутствия компьютера внутри, а потому что уроки труда (и отец) учили совать отвёртку в начинку. И главное — детали можно было менять, не оскверняя священную гарантию.

Так было устроено многое. Теперь — нет. Отчасти потому, что софт повсюду и непостижим обычному человеку, отчасти потому, что корпоративные хищники знают: на подписках и сервисе наживаются больше, чем на готовых изделиях. (Нет смысла открывать Prius, «чтобы посмотреть двигатель»: это компьютер, обёрнутый машиной; производитель к тому же физически ограничивает доступ к начинке, чтобы брать за Авторизованный сервис сколько захочет.)

В нынешнем мире, где большинство потребителей и все «молодые взрослые» охотнее платят социопатам за ограниченный доступ к потоковой музыкальной библиотеке, чем владеют носителями, и почти вся телекоммуникация идёт через «огороженные сады» корпораций — где «творческие инструменты» в основном служат потреблению (ремиксы, фанфик, «мемы»), а не рискованным попыткам новой самовыразительности — интерпассивное потребление и ожидается, и всё чаще исключительно допускается. (Интерпассивность: поручить DVR «посмотреть» телевизор за вас, чтобы можно было больше работать, не опасаясь пропустить «свои» шоу.)

Когда нормисы хвалят технологию за то, что она «просто работает», вкладывают они в это не то, что инженеры. Для нетехнических людей «просто работает» значит «позволяет продолжать не думать». Удачная потребительская техника должна впечатлять, а не наделять силой; часто достаточно произвести впечатление — и доверчиво‑неграмотный решит, что «оно просто работает». Понимающие люди употребляют ту же фразу иначе — чтобы похвалить надёжность, прочность, функциональность: «просто работает» — это когда можно рассчитывать на верный полёт в любую погоду, освобождая людей не для отдыха (будьте серьёзны!), а для другой работы.

Пожалуй, это ключевое различие: одни ценят технологии, позволяющие делать больше — эффективнее и результативнее; другие ценят технологии, позволяющие делать меньше — в абсолюте. (Мудрые люди[fn:16] ценят и то и другое, знают, когда что важно, и не путают бездействие с досугом.)

Сравните безобразный, но чудовищно мощный язык взаимодействия Emacs с запоминаемыми «горячими клавишами» и жалко ограниченными возможностями обычного редактора. Сравните отлаженную плавность дедовского перочинного ножа, как он выскальзывает лёгким щелчком кисти, — с неохотным ходом мультитула, купленного для бесконечного «дедовского косплея», но реально используемого лишь для вскрытия коробок FedEx, да и то чаще остающегося дома, чтобы не ломать чистую линию дизайнерских «тактических» брюк… Это разница между функциональными инструментами и театральными реквизитами; между миром, который требует энергии на запуск, но способен стать прекрасным — магическим, — и миром, где жить легко на поверхности, но невозможно в долгую: платишь собой и ржавеешь душой.

Инструменты, позволяющие делать работу сложнее и лучше, — благословение; инструменты, делающие жизнь легче, но хуже,[fn:17] — другое дело, даже если с детства нас учат ценить именно их.

Выбирая формы и инструменты, которые дают возможность быть правым — ценой испачкаться, попыхтеть или столкнуться с ужасом крутого порога вхождения, — мы соглашаемся жить под углом к «обыденному опыту» (и к собственному внутреннему представлению о том, «как должно быть», вынесенному вовне голосу суперэго). «Настоящая работа» всячески отстаивает эту неуютную, но напряжённо плодотворную двойственность, общую странной мысли и намеренной практике, — чувство «в мире, но не вполне от мира». Это и участь художника. Пройти мимо лёгкого удовлетворения к глубокой полноте — значит отвергнуть манию удобства, ядро нашей светской потребительской государственной религии, — и принять, не без риска, альтернативную реальность вне консенсуса.

(Легко мне рассуждать, конечно, из нашей хорошей квартиры в благоразумном городе с электромобилем на собственной парковке.)

Наш разговор о верующих, ведущих «две книги», связан с этим чувством «принадлежности‑отчуждения»: молящийся должен жить с фактом, что есть существо, слушающее и отвечающее на его молитвы — а именно/только его собственный ум, — и потому невыносимые фикции и метафизическая нелепица организованной религии повсеместно уступают место неортодоксальной индивидуальной практике — близким личным отношениям с внутренним «кем‑то», кого нет, но кто помогает нам в нужде, — а потому подлинная жизнь верующего везде — жизнь «удовлетворённой неудовлетворённости». Преднамеренная жизнь с/в открытых вопросах и незакрытых парадоксах — вместо (продаваемых, но ложных) «удовлетворяющих ответов» — может привить иммунитет к некоторым тупым идеологическим нажимам, но это страшно, одиноко и больно — хорошо ещё, что церкви дают социальные компенсации за ужас, через который протаскивают адептов их системы веры.

* Доступ к инструментам

Emacs — это ставка, что не сыграла, на будущее, которому никогда не дадут случиться. Он воплощает обаятельную, но ошибочную веру в то, что создание инструментов, делающих людей свободнее, запустит движение к свободе. Если бы его делали панки, а не хиппи — не учёные и инженеры, жившие на наивной меритократической надежде, — возможно, движение, которое он представляет, умело бы требовать, а не напоминать.

Каждый раз, садясь за компьютер и открывая Emacs, я вхожу не в «будущее», а в исчезнувшее будущее исчезнувшего прошлого — и мне дают доступ к несравненной силе, — и от этого у меня разрывается сердце.

* Имплицитность

Вам продают посудомойку или машину, или программу — и цена того, что чинить «самому» вроде как не придётся, в том, что чинить вам не позволено. «Защита», которую якобы обещает гарантия, — не для вас, а для компании: гарантия существует, чтобы её нарушали, как закон о наркотиках, ставя вас в положение нарушителя — и тем освобождая Их от каких‑либо обязательств помогать. Она производит нарушения, и только. Гарантия описывает их ответственность так, чтобы рядовые разумные действия освобождали их от неё; юристы потому и так хорошо оплачиваются. Ваша работа — оставаться зависимым, и ваша награда — инфантильное «счастье». Ваша другая работа — молчать.

Один из догматов/симптомов метастатического капитализма: если вы не владелец бизнеса, вы не решаете, чему быть в мире; «создание» сведено к производству и принадлежит исключительно капиталу и его смотрителям/слугам; владельцы, инвесторы решают, что считается. «Мейкерам» дозволено печатать на 3D‑принтере безделушки, подставки для ноутбука, крючочки для полотенца у плиты, неденоминационные подарки для воспитателей их детей в Монтессори и т. п. Им позволено быть дарителями; им запрещено менять и ставить под вопрос данное. Выйти за пределы этого буквально производимого консенсуса, «выйти из сети», — значит жить «неправильно». Один из тяжких грехов против порядка — пытаться расширить круг возможного, познаваемого, делаемого, не монетизируя это и не делая любые новшества/создания легитимными для капитала. Хороший гражданин «заложил бы чёрный ход». Вам уж точно не положено действовать свободно, т. е. аутентично, в анти‑творческом, хищно‑ассимиляторском порядке; порядок дан, разве не ясно? Им нужно, чтобы осмысленная автономия оставалась буквально немыслимой, и потому все подлинно свободные переживания клеймятся (более или менее тонко) как — возьмём репрезентативно — «медленные, корявые, древние, непостижимые, чрезмерно сложные, эргономически катастрофические и просто уродливые». Дальше: грязные, опасные, странные, бредовые, немодные, неутончённые, анархические, проблемные, вредные…

А уродство — хуже всего: оно оскорбляет вкус Надзирающего Ока.

«Внешние» опыты вызывают неприятное напряжение — и по объективно биологическим, и по дурным, управленческим соображениям. Контрапозиция в действии: если ты достоин управлять собственной жизнью — ты был бы богат. Если ты способен думать сам — мы бы, разумеется, дали тебе разрешение; а если ты справился бы с ответственностью за эту машину, все уже знали бы, потому что мы им сказали. Ты там, где должен. Рядом.

Думать иначе — пасть жертвой бреда, гордыни, фантазии, «магического мышления». Это чудовищно, мерзко… как Ричард Столлман, скажем.[fn:18]

Пока производственные процессы тщательно управляются и предсказуемы — ср. гипероптимизированный голливудский конвейер, уже не способный выпускать ничего, кроме сиквелов, — именно неопределённость и неустойчивость творческих практик делает их воображательно плодородными; взрывной рост — взрывной, созидание — риск. «Тот опасный элемент»: страшная возможность стирания категорий, мир под ногами вдруг переворачивается, оказывается достаточно большим, чтобы нас съесть, зеркально‑изменчивым. Пикардийская терция, благопристойная инверсия мультивселенной — о, оставьте Джойсу, лишь шалость для всех. Мы, обезьяны с инструментами, инстинктивно тянемся к опыту «вне категорий», неузнаваемой «ощущаемости во рту», тотальной странности — привычные дневные «я» сдуваются пеплом, — но это и пугает: в сумерках пройти внутрь/наружу в нечто (в другого нас), заново сотканное ночью. Всем иногда нужен визит к экзистенциальной опасности, но к рабочей (школьной) ночи хочется защиты от такого тёмного искусства. «Кто‑нибудь, заберите у меня ключи: мне доверять нельзя».

Ну… а есть люди, готовые сделать пребывание в двойном‑секретном промежутке своей работой — кому милее равновесие (equipoise), чем поза (poise). Готовые вкладывать труд в сам «магический труд», исследовать создание инструмента, а не только пользоваться им. В когнитивной сфере — скажем, серьёзная медитация, развитие памяти, нейропоп‑наркотики, если уж очень; взлом сознания. «Второй ум». (Считайте, я здесь напрашивался на очевидные параллели с Emacs и магической работой.) Ино: «касательные способы атаковать проблемы… во многих смыслах интереснее, чем прямой, лобовой подход». Звучит как уйма работы — но мы с вами не сделали Another Green World. (Если это читаешь ты, Брайан — стукни раз для «да»…)

Вместо инструмента, который сводит мир к управляемости, вообразите метаязык для описания и конструирования инструментов, целую платформу — подумайте о том, как Фил Хайн решает, с какой тульпой слиться сегодня, как добиться союза, не зная, что получится. В любом случае будет — большое. Вы бросаете монетки в темноту — и если даже одна из тысячи вернётся, вы сделали первый шаг в больший мир.

Парень‑фермер сказал: «Знаешь, я и вправду кое‑что почувствовал. Я почти видел…» Так и навязывайте «категориальную ошибку»: оставайтесь непереводимыми, непродаваемыми. Свободны — свободны как слово, как радикальность, как в «Free your mind and your ass will follow», как в «Разве ты не видишь ничего, что хотел бы попробовать?» Прекрасное создание, которому не хватает только приличной категории.

Инструменты для интроспекции — а не телекоммуникации.

Говорят (кто?), что заклинания и молитвы не работают, но молитвы и заклинания — технологии интроспекции и психотропизма с социальным действием как побочным эффектом; разумеется, они работают — они просто не творят чудес, да их никто и не творит. Не стоит требовать от магии мирского стандарта — или сравнивать нож с кузницей, а МКС — с тщательно курируемым дизайнерским «Приложением для авторов».

Трансгрессивное напряжение — сущность творческого исследования и магической работы, нервный задор копания под консенсусными категориями, зарывания слишком глубоко, чтобы быть «узнанным», — а современная потребительская антикультура отрезает эти ощущения «из благих побуждений». Моэлы на дом[fn:mohel]. Система[fn:19] оправдывает «оставаться на месте» в материальном нулевой суммы тем, что делает «междусть», временность и некрасивую автономию грехом, формой падения. «Выпасть из шага», не поспеть (ведь как можно отказаться?) за соседями Джонсами. Но вместо ритуальной сдачи чужой трусости вы можете говорить или ~self-insert-command~ свои слова силой; мы могли бы ковать «я», а не безделушки, выбирать гражданскую субъектность вместо потребительского довольства. Мы можем вести две книги — чтобы было что показать тем тревожным доброхотам, которые держат свои монетки «в безопасном месте» и не желают слышать про призраков, лиспы и «экстатхи стттранных синтттезов»…

* Двойственность

Базовая идея в программировании: «функция» или «подпрограмма» — связка инструкций, часть большей программы, которую может вызывать другой код — имеет возвращаемое значение, полезное вызывающему коду. В адресной книге может быть подпрограмма alphabetizeContacts(contactList), получающая список имён на вход и возвращающая его же, но отсортированным, — вызывающему коду. Идея в том, что любая часть программы может вызвать эту функцию, зная, что ей передать и что получить; более того, внутренности alphabetizeContacts() можно менять, не ломая общий ход, если функция по‑прежнему ожидает список контактов и выдаёт отсортированный. Среди прочего, когда функция «возвращает», машина знает, что она перестала вносить изменения. Возврат — своего рода гарантия, контракт.

Помимо возвращаемого значения подпрограмма может иметь побочные эффекты — и это то, как звучит. Она может показать что‑то пользователю, увеличить счётчик — сотню дополнительных действий, явных или нет. Отладка сложной программы часто означает трассировку и управление побочными эффектами, поддержание течения программы чистым и обозримым; искусный дизайн — это дисциплины инкапсуляции и абстракции, аккуратное управление «состоянием» — не только в бытовом смысле «что, по мнению пользователя, происходит?», но и в техническом «каково значение каждой переменной, что и где хранится в памяти?» «Состояние» — отчёт о «внутримире» программы — надеемся, познаваемом, но бывает — нет.

Важнейшее: функции и программы нередко пишутся так, что то, что они «на самом деле делают» (в бытовом смысле), — строго побочный эффект их формальной, определённой цели. Каким именно образом информация попадает на разные экраны, может быть неважно для внутренней логики — поэтому код отображения — отдельная забота, — но без него программа бесполезна человеку. Иными словами, «побочный эффект» — это деятельность, не схватываемая «идентичностью» порождающего процесса, но при этом могущая быть центральной для его роли в мире.

* Главное — не всегда главное.

К слову о главном: функция ~main()~ в программе на C — главный процесс по умолчанию, условно ограничивающий вселенную программы — возвращает целое число: вверх или вниз, теоретически — индикатор удачного прогона или второго варианта. Или число, или ничего. Некоторым покажется, будто это исчерпывающее описание всякой физической деятельности Вселенной; как только усвоишь идею «абсолютного нуля», температуры, при которой всё движение замерзает (‑273.15 °C, с поправкой на эмпирику), в финальном return 0, завершающем прогон, есть что‑то чуть жуткое…

(Правда, во вселенной C return 0 — хорошие новости; прочие коды возврата — симптомы непотребства, как шаркающие шаги в тишине после Большого Схлопа…)

«Настоящая работа» употребляет термин «побочный эффект» именно в этом смысле, потому что магия[fn:20] — вся из побочных эффектов. Один из наших стержневых тезисов: для индивидуальной и коллективной психической здравости нам нужно распознавать и использовать дистанцию между явными, «сознательными», именованными действиями и побочными эффектами — иногда прикрытыми фиктивной надстройкой — которые на деле составляют большую долю работы нашей жизни. Это альтернативная версия темы «двух книг» в «настоящей работе», указывающая на намеренную деятельность, невидимую даже для исполняющего её ума, потому что она нарушает структуру ожиданий этого ума. («Всякое видение — это видение‑как»; мы не видим того, чего не знаем.)

Подумайте, как молитва будто бы «проваливается», потому что никто, кроме нас, не слушает — нет возврата, так сказать; пустота — хотя смиренное признание и есть цель деятельности, её психологический источник ценности. Эта ценность трудна для стороннего наблюдателя, а «фиктивная надстройка» по имени «Бог» может скрывать эту психологическую работу и от самого молящегося; на самом деле так и лучше — иначе он мог бы не дойти до исповеди. Аналогично, развязка сюжета выглядит «выплатой» выдуманной функции‑машины, но её побочные эффекты — внутренние циклы напряжения и разрядки, последовательные и параллельные позы читателя: удивление, подчинение, суд, рассуждение, отождествление — вот реальная субстанция отношений читатель/фикция, а не «счастливый конец» как ~return 0~ внизу горки.

Вот почему подло и глупо спойлерить финалы — другим или себе — вмешиваясь в непрерывный и намеренно выстроенный эмоциональный контур. Мы читаем, чтобы быть меньше истории, быть внутри, а не чтобы «получить и владеть» сведениями о сюжете — иначе нам и история не нужна, хватило бы синопсиса. Нужно сопротивляться соблазну обокрасть себя — не только в откровении, но и в догадке. Смирение наделяет силой.

Нам нужна действенная психология магии и бессмыслицы.

Пользуясь инструментом вроде молитвы или Emacs, или медитацией, или (чтением) романа, пользователь (проситель, вопрошающий) прямо уделяет внимание доступному интерфейсу, внешней надстройке, в то время как глубинная работа идёт вне поля зрения. Вы открываете книгу, чтобы узнать, что будет дальше, но чтение, удивление, размышление вас меняют, переводят и расширяют; вы сосредоточиваете внимание на дыхании, свечном пламени или мантре, чтобы сосредоточить внимание, — в то время как означивание распадается; вы просите Бога, а затем отвечаете сами; вы бродите через «интерактивную фикцию», решая лишь серию логических головоломок; вы заходите в универсальную программируемую среду и занимаетесь только редактированием текстов; и всё это время позади (или под) вами открыта дверь — осталось понять природу и рукоять инструмента, заметить и назвать побочные эффекты, уловить невысказанную цель, шагнуть в лабиринт одинаковых извилистых проходов. «Играй, чтобы узнать, что будет».[fn:21]

* Самопознание — инструмент выживания.

Первое, что надо узнать, — свою двойственность — свою множественность. Есть чтения попроще и редакторы подружелюбнее, но странный рост человеческой души зависит от пути. «Вера» — путь неопределённый, с неизмеримой целью. Чтобы умело идти миром, откажитесь от лёгких удовлетворений и следуйте со страшной, как во сне, строгостью. Идентифицируйте действующие фикции и работайте ими напрямую — почему нет? Воображаемые цели предполагают воображаемые средства.

Когда программа выполняется, вывод — рост и смерть, ~return 0~; но происходит ещё кое‑что.

Emacs — «свободный софт» в том смысле, что он верит в возможность вашей свободы. Он хочет для вас этого хорошего; он воплощает этот дух. Ему не хватает только приличного редактора — хотя он здесь, чтобы помочь вам собрать свой — и меньшие справлялись.

И богов нет, так что на свои молитвы отвечаете вы сами, у вас нет выбора, и что бы ни отвечало вашим молитвам — это бог, а не наоборот. Это всегда был секрет, вопрос к конечному ответу: мы как боги, и нам бы стоило git gud — прокачаться в этом.


* M‑x isearch-backward

Одна из причин, по которой практик «магии» фетишизирует старину: с прошлым сперва нужно согласиться — признать, что оно случилось. Выбора нет: оно реально и записано. История — это процессия невероятных (проклятых!) фактов, от которых не сбежать, — так что сиди с ними, даже с невероятным и кажущимся невозможным, один странный тезис за другим. И признавай, что оно не исчезает, когда ты отворачиваешься; след всегда остаётся. Прошлое — для жизни рядом, прежде всего в лице родителей, разумеется. Огромно, как горы, — зачем пытаться сдвигать. Мыслить магию как невозвратное прошлое «только для чтения» — прагматически настраивает нас принимать его на его условиях — если только мы не мудаки… Один враг — презентизм, то бишь «протагонизм», а побочный эффект покупки тусклого мифа о «Золотом веке» — подцепиться к нашим нарративным аппаратам, подготовить нас к принятию — то есть вы обязаны — дабы умело обратиться к настоящему, которое нас занимает. К основной линии. По прошлому можно писать поверх — оно впитывает. Фактически оно утрачено нам, но по‑прежнему присутствует как история; дистанция делает невозможное правдоподобным как фиктивная надстройка.

Прошлое — парадокс, лабиринт и логово; руина, обнажающая реальное, но нереалистичное; регресс‑процессия уроков.

Emacs сегодня тяжело обрести новую аудиторию; теперь труднее, чем раньше, начать «неправильно». Но он приходит к нам из прошлого на своих условиях, старше и страннее жизни. Сделанного не воротишь. Большинство его оставит — как кошмар, от которого хочется очнуться, — но некоторые берут и находят. «Приобретённый вкус».

Вы не поймёте, пока не начнёте пользоваться; вы не увидите, пока не поверите. Магический круг должен замкнуться вокруг действия, а вера — сделать момент из времени; прошлость делает эту трансформацию возможной, как и фикция, — их воображаемые контракты превращают декорации сцены в древне/альтернативные где‑когда. Мы используем прошлое, чтобы переосмыслить своё действие как «возврат/открытие», и двинуться дальше с чуть меньшей импотентной самосознательностью о «Где» и «Как». (Или можно мифологизировать сами «Где» и «Как», сделать technē фокусом; научный метод тоже требует веры — разумной.) Былое — просто есть, и это хороший старт.

Говорят: нет Emacs — есть только ваш Emacs.

#+begin_quote
«Your Glorantha Will Vary» (HeroQuest Glorantha, стр. 4, 114, 130, 144, 221 и 222)
#+end_quote

Я про то, что у времени есть вес. Приход в странные старые текстомиры именно сейчас — особый опыт; чувство руины и восстановления несёт сложный заряд, специфичный для «большой/малой» разницы десятилетий — между их «там‑тогда» и нашим «здесь‑сейчас»; эта дистанция даёт нам некоторую безответственность, свободу читать и бежать — что может оказаться чёрным ходом к настоящей ответственности. Побочные эффекты, боковые истории, косые стратегии. Отстранение превращает вовлечение — и мааaybe подталкивает действовать с верой («альтернатива — страх»), привыкать двигаться по незнакомым пространствам и формам, новым странным углам себя.

Есть что сказать в пользу старых способов, старых миров, мод, стариков; к лучшему или худшему мы устроены относиться к ним иначе. Дай дорогу и поддержи дверь. Есть эволюционная причина у «Жили‑были» — что‑то про тактику фиктивного убеждения и направленность стрелы времени, пользу данности. Вы не поймёте, пока не начнёте: нас заряжает то, что мы ищем и находим, и работа, которую мы вкладываем в миротворчество — копание, — в свою очередь конституирует наши отношения с многими нашими мирами. Отсюда травматическая сцепка и «а можно я расскажу про своего персонажа», и тот первый роман, который вы никогда не закончите, и странная живучесть текста против пронзительности изображения, прошедшего светом из прошлого: смысл меняется от того, как мы его делаем, от воображаемых метаданных, которыми сопровождаем. Эти побочные эффекты. Отсюда и разница (см.) между укоренённой «уверенностью» и воздушной «определённостью». Первая приходит от работы с информацией — ощупью, «через пальцы», — от вывертывания наружу и внутрь; вторая — уклонение. Невесомость. Быть «определённым» можно только насчёт инструмента, который ещё не взял в руки — как сказал Эмпсон: «…один лишь предохранительный клапан / Знает худшую правду про двигатель; только ребёнок / Ещё не введён в заблуждение».

(Санта‑Клаус — воспитательный инструмент.)

Уверенность рождается от проверки; мир, как любовь, нужно делать. Умонастрой создателя инструмента отличается от настроя пользователя, и тем более от потребителя; первые двое могут встретиться внутри изгиба и зерна вещи и действия — в общем термине «создания и владения», — но те, кто псевдосвязывается лишь через посредство Доллара, навсегда отрезаны от истины, открытой лишь тем, кто берёт рукоять и защёлкивает защёлку. Идентичность «потребителя» отрезает истинное знание — в этом её дело. «Деньги», между прочим, именно для этого: обезличить обязательство в долг без отношения.

Я не должен «тебе» — я «должен деньги».

Воображаемое со‑творение текстомира: нет Emacs, кроме вашего; нет Nomic или Viriconium вне понятия (ваше будет отличаться), но есть вот это — «играй, чтобы узнать». Этот лабиринт — не «хобби», а «образ жизни» — вернее, какая‑то нестильная жизнь под неверным словом: медленный поворот от накопления к интеграции, как от земной арканы к внутренней и космической. Вы отвечаете на свои молитвы — то есть существует вселенная, где Бог есть, — и это вы; купленное может быть приятно, но верное — найдено; его надо выкапывать, и всякая яма, которую вы не перестаёте копать, — это ход. «И кровь его — на вкус как моя?» Если у вас Harley, вы можете вступить в клуб, но это не должен быть «заводской» Harley — доказательство подлинности — в действии, даже в действии «инаковости». Ваши привязки клавиш будут варьироваться, потому что варьируетесь вы. Вы выбираете существительные и глаголы: когда мы говорим словами хозяина, мы думаем—

Нам стоит быть более скептичными к мирам, которые создаём, и более доверчивыми — вопреки рациональности, — ради миров (внутренних и иных), которым только предстоит быть созданными. Нам стоит умнеть, чтобы не оптимизировать преждевременно ради порядка, когда вся‑вся стрела времени указывает внутрь и вниз — к абсолютному ~return 0~. Слова мудрости, пусть будет так: ваш мир — прекрасный поток сознания, которому недостаёт лишь приличного редактора.

#+begin_quote
И я тоже, … когда подозреваю, что облажался по полной, остро ищу уединения. Неправильный сейчас час… Мы, кто станет объектом Его гнева, должны держаться рядом и говорить напрямик. Альтернатива — бегство. Влечёт? … Мы не из таких, и в этом, может быть, больше жалости. (Дэвид Милч, Deadwood 3×06, «A Rich Find»)
#+end_quote

— — —

[fn:1] Оставаясь в «чистом тексте» с лёгкой разметкой, нетрудно собрать модульный издательский конвейер в юникс-стиле — надёжные маленькие части, свободно сочетаемые. Этот проект опирался на multimarkdown-файлы под git (и GitLab), на pandoc для веб-выдержек и «быстрого принта», на LaTeX и бесценный класс memoir для печатной вёрстки, а также на россыпь shell-скриптов для нормализации и укладки данных. Альтернатива здравым текстовым потокам — привязаться к MS Word или Scrivener (ха-ха) и стараться не думать об интеропе, экспорте и зависимости от платформ. Я — счастливо «бывший» пользователь бутик-редакторов вроде iA Writer, OmmWriter и Ulysses.

[fn:2] Возможно, я просто «слишком стар для этого дерьма», но вернитесь ко мне через пять лет, когда помолодею. И да: Emacs переосмысляет большую часть vim как альтернативную модель взаимодействия в ~evil-mode~, чего более чем достаточно, чтобы не‑маги воспринимали его как слегка более медленный «vim плюс плюшки», чьи странности окупаются доступом ко всей вселенной Emacs. Настолько Emacs суров.

[fn:3] В земле Emacs это записывают как ~C‑c C‑a f~ и ~C‑x C‑f~, поскольку регистр важен, т. е. f ≠ F. Будучи вменяемым взрослым, я теперь нахожу регистронепрозрачность «Ctrl‑F значит “Find”» слегка оскорбительной. Заметьте, это лишь значения «по умолчанию»; ваши привязки могут отличаться — хотя, распробовав стройную и последовательную логику, возможно, менять ничего и не захочется.

[fn:4] Emacs и Vim действительно рождались на/для клавиатур из других вселенных.

[fn:5] Я слегка сгущаю краски. Наберите M‑x и начало имени команды — и система дополнения подскажет варианты; начните последовательность — и which‑key покажет «шпаргалку» для составных шорткатов и аккордов. Разумеется, инкрементальный поиск можно «замыкать», а можно просто поставить пакет swiper. Неловко «усиливать» претензии к Emacs, ибо по сути внятных — две: «не хочу тратить время, чтобы добраться до порога окупаемости» и «начальство велело сидеть в VS Code».

[fn:6] Путаница упирается в недопонимание термина «буфер» (buffer). Даже новичкам Emacs придётся в этом разобраться.

[fn:7] Под Lisp лежит C‑код, обслуживающий базовые действия на высокой скорости, но заинтересованный пользователь может изменить почти любой пользовательский аспект Emacs изнутри программы. Бесстрашные спелеологи могут ковыряться и в исходниках — разумеется, открытых.

[fn:8] M‑ здесь означает модификатор meta, которого больше нет на клавиатурах; обычно его вешают на клавишу Windows или на Command (⌘), но мне по душе Option — под средним пальцем на домашнем ряду. Есть ещё «super» — я вызываю его, произнося кровожадные формулы и шлёпая себя по лицу.

[fn:9] «Мы как боги — и нам бы следовало стать в этом хорошими. Пока что удалённые пути власти и славы — правительство, крупный бизнес, формальное образование, церковь — преуспели настолько, что грубые дефекты заслоняют реальные достижения. В ответ на эту дилемму и на эти достижения возникает область интимной, личной силы — силы индивида вести собственное обучение, находить собственное вдохновение, формировать собственную среду и делиться своим приключением с каждым, кому это интересно. Инструменты, помогающие этому процессу, разыскиваются и продвигаются WHOLE EARTH CATALOG». (Заявление о цели Стюарта Брэнда)

[fn:10] Глава 25 руководства Emacs так и называется: «Команды для человеческих языков», которые с точки зрения машины, понятно, второсортны.

[fn:11] Да, легкомысленная аллюзия на Деррида в эссе о текстовом редакторе. И да, я помню, что это каламбур/двусмысленность, а его странно обесценивающие пост‑hoc оговорки о двусмысленностях собственной прозы не стоит принимать за чистую монету — ровно как и саму прозу. Ему колоссально повезло говорить одновременно как игривый философ‑каламбурист и «неправильно понятый» правдолюб в затяжной партизанской войне против якобы тирании дуализма. История с Гаятри Спивак, прочитавшей в Нью‑Йорке длинный доклад о том, что деконструкция «по Деррида» не поддаётся предписанию, а затем шуточно выложившей нумерованный список тропов практики — по-своему комична; тем забавнее, что сам Деррида поднялся и сказал: «Вообще-то это почти оно». Годы «Теории» принесли мне много чепухи, но это был или пик, или дно — как на чьё настроение.

[fn:12] В исключающе‑эзотерическом жаргоне «GNS»‑теории игрового процесса Рона Эдвардса можно сказать, что наше «системное воображаемое» отражает симуляционистскую или «системо‑исследовательскую» повестку.

[fn:13] Да‑да, я знаю, что это не его имя, и знаю, что бестселлерный американский «Руми» — по сути демиелинизированная версия Коулмана Баркса, — да, да.

[fn:14] В психоделической классике Моррисона/Куайтли All‑Star Superman Супермен побеждает буйствующего Лекса Льютора, дав ему то, чего тот всегда хотел, — силу бога. Лютор видит всё, везде и сразу — и парализуется откровением: «Вот так он видит всё время, каждый день. Будто тут только мы, внутри, вместе. И у нас только мы и есть». Час сюжета истёк, способности Лютора рассыпаются, и он визжит на всемогущего пришельца: «Я мог спасти мир, если бы не ты!!» Кларк бьёт его. «Ты мог спасти мир много лет назад, если бы это имело для тебя значение, Лютор». Вот граница — и бремя всемогущества.

[fn:15] Наша терминология намеренно отсылает к «General Theory of Love», где «любовь» понимается как набор протоколов коммуникации, обеспечивающих эмоциональное содействие совместному развитию посредством лимбического резонанса (со‑настройка), лимбической регуляции (стабилизация) и лимбической ревизии (переобучение). Эта книга даёт объединённое понимание «любви», связывающее интимный физиологический процесс регулировки сердцебиения у младенцев с «действием на расстоянии» — сонетом, то есть я буквально идеальная её целевая аудитория, и я в большом долгу перед её авторами Льюисом, Амини и Лэнноном — долг, который «настоящая работа» пытается выплатить.

[fn:16] Я думал о моём дорогом друге Джереми, пока писал это, — человеке, которому порой трудно расслабиться, но который знает и ценность, и удовольствие этого, и старается сделать мир таким, чтобы другим было безопасно и возможно выдохнуть и жить. Джереми — хороший человек.

[fn:17] Подумайте о героине, «знакомствах онлайн», потоковом видео, Uber, AirBnB и Twitter; а затем (эх, почему бы и нет) — о дерегулировании, массовой слежке, ИИ‑искусстве, инфляции оценок и «снижении вреда».

[fn:18] (РМС и правда мерзковат, как подтвердят те, кто его у себя принимал во время конференций и выступлений, — но не из‑за своих философских убеждений.)

[fn:19] Даже спустя все эти годы мне приятно насмешливо говорить «Система» и подтрунивать над «продажными». Поколение X рулит!

[fn:20] Ключевой тезис «настоящей работы» — что термин «магия» подходит к большинству человеческого опыта — даже к вашему.

[fn:21] Эта строка — из советов ведущему (MC) в ролевой игре Винсента Бейкера Apocalypse World — образцовой в своём роде. «Играй, чтобы узнать, что будет» звучит очевидно, но в одержимом «миростроением» мире настолок (и особенно в тревожном, беспомощном микромире «сторигеймов») это — развязывающее заклинание. В «игрокнижке» MC у Бейкера есть и такие же мудрые бейзлайны для мастера любой ролевки: «Смотри через прицел… Задавай провокационные вопросы и стройся на ответах». И лучшая: «Отвечай подлянками и нерегулярными наградами».

[fn:mohel] Моэль — обрезатель в иудаизме; ритуальный специалист, совершающий обрезание.

